"""
51-jurisdiction registry metadata for U.S. state company registries.

Each entry describes:
- jurisdiction_code: canonical code (us_XX)
- name: full state name
- sos_url: Secretary of State search URL
- tier: bulk | api | scrape | cobalt
- adapter_module: Python module path (relative to state_registry package)
- adapter_class: class name
- notes: any special notes
"""

JURISDICTIONS: dict = {
    "us_al": {
        "jurisdiction_code": "us_al",
        "name": "Alabama",
        "sos_url": "https://arc-sos.state.al.us/CGI/CORPDETAIL.MBR/DETAIL",
        "search_url": "https://arc-sos.state.al.us/cgi/sosb/amiact.mbr/input",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ak": {
        "jurisdiction_code": "us_ak",
        "name": "Alaska",
        "sos_url": "https://www.commerce.alaska.gov/cbp/main/Search/Entities",
        "search_url": "https://www.commerce.alaska.gov/cbp/main/Search/Entities",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_az": {
        "jurisdiction_code": "us_az",
        "name": "Arizona",
        "sos_url": "https://ecorp.azcc.gov/EntitySearch/Index",
        "search_url": "https://ecorp.azcc.gov/EntitySearch/Index",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ar": {
        "jurisdiction_code": "us_ar",
        "name": "Arkansas",
        "sos_url": "https://www.sos.arkansas.gov/corps/search_all.php",
        "search_url": "https://www.sos.arkansas.gov/corps/search_all.php",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ca": {
        "jurisdiction_code": "us_ca",
        "name": "California",
        "sos_url": "https://bizfileonline.sos.ca.gov/search/business",
        "search_url": "https://bizfileonline.sos.ca.gov/search/business",
        "tier": "api",
        "adapter_module": "us.state_registry.api.ca",
        "adapter_class": "CaliforniaSOSConnector",
        "notes": "CA_SOS_API_KEY optional; falls back to scrape",
    },
    "us_co": {
        "jurisdiction_code": "us_co",
        "name": "Colorado",
        "sos_url": "https://www.sos.state.co.us/biz/BusinessEntityCriteriaExt.do",
        "search_url": "https://data.colorado.gov/resource/4ykn-tg5h.json",
        "tier": "bulk",
        "adapter_module": "us.state_registry.bulk.co",
        "adapter_class": "ColoradoBulkConnector",
    },
    "us_ct": {
        "jurisdiction_code": "us_ct",
        "name": "Connecticut",
        "sos_url": "https://service.ct.gov/business/s/onlinebusinesssearch",
        "search_url": "https://service.ct.gov/business/s/onlinebusinesssearch",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_de": {
        "jurisdiction_code": "us_de",
        "name": "Delaware",
        "sos_url": "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx",
        "search_url": "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
        "notes": "JS-heavy portal; may need Playwright",
    },
    "us_dc": {
        "jurisdiction_code": "us_dc",
        "name": "District of Columbia",
        "sos_url": "https://corponline.dcra.dc.gov/Account/LogIn",
        "search_url": "https://corponline.dcra.dc.gov/Account/LogIn",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_fl": {
        "jurisdiction_code": "us_fl",
        "name": "Florida",
        "sos_url": "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName",
        "search_url": "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName",
        "tier": "bulk",
        "adapter_module": "us.state_registry.bulk.fl",
        "adapter_class": "FloridaBulkConnector",
        "notes": "SFTP sftp.floridados.gov public creds; falls back to HTTP search",
    },
    "us_ga": {
        "jurisdiction_code": "us_ga",
        "name": "Georgia",
        "sos_url": "https://ecorp.sos.ga.gov/BusinessSearch",
        "search_url": "https://ecorp.sos.ga.gov/BusinessSearch",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_hi": {
        "jurisdiction_code": "us_hi",
        "name": "Hawaii",
        "sos_url": "https://hbe.ehawaii.gov/documents/search.html",
        "search_url": "https://hbe.ehawaii.gov/documents/search.html",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_id": {
        "jurisdiction_code": "us_id",
        "name": "Idaho",
        "sos_url": "https://www.accessidaho.org/secure/sos/corp/search.html",
        "search_url": "https://www.accessidaho.org/secure/sos/corp/search.html",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_il": {
        "jurisdiction_code": "us_il",
        "name": "Illinois",
        "sos_url": "https://www.ilsos.gov/corporatellc/",
        "search_url": "https://www.ilsos.gov/corporatellc/",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_in": {
        "jurisdiction_code": "us_in",
        "name": "Indiana",
        "sos_url": "https://bsd.sos.in.gov/PublicBusinessSearch",
        "search_url": "https://bsd.sos.in.gov/PublicBusinessSearch",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
        "notes": "Official bulk ~$8-9k; scrape for MVP",
    },
    "us_ia": {
        "jurisdiction_code": "us_ia",
        "name": "Iowa",
        "sos_url": "https://sos.iowa.gov/search/business/(S(x))/search.aspx",
        "search_url": "https://sos.iowa.gov/search/business/(S(x))/search.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ks": {
        "jurisdiction_code": "us_ks",
        "name": "Kansas",
        "sos_url": "https://www.sos.ks.gov/sos_business_services.aspx",
        "search_url": "https://www.sos.ks.gov/sos_business_services.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ky": {
        "jurisdiction_code": "us_ky",
        "name": "Kentucky",
        "sos_url": "https://app.sos.ky.gov/ftsearch/?path=serv",
        "search_url": "https://app.sos.ky.gov/ftsearch/?path=serv",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
        "notes": "Official bulk ~$2k/month; scrape for MVP",
    },
    "us_la": {
        "jurisdiction_code": "us_la",
        "name": "Louisiana",
        "sos_url": "https://coraweb.sos.la.gov/commercialsearch/CommercialSearch.aspx",
        "search_url": "https://coraweb.sos.la.gov/commercialsearch/CommercialSearch.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_me": {
        "jurisdiction_code": "us_me",
        "name": "Maine",
        "sos_url": "https://icrs.informe.org/nei-sos-icrs/ICRS?MainPage=x",
        "search_url": "https://icrs.informe.org/nei-sos-icrs/ICRS?MainPage=x",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_md": {
        "jurisdiction_code": "us_md",
        "name": "Maryland",
        "sos_url": "https://egov.maryland.gov/BusinessExpress/EntitySearch",
        "search_url": "https://egov.maryland.gov/BusinessExpress/EntitySearch",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ma": {
        "jurisdiction_code": "us_ma",
        "name": "Massachusetts",
        "sos_url": "https://corp.sec.state.ma.us/CorpWeb/CorpSearch/CorpSearch.aspx",
        "search_url": "https://corp.sec.state.ma.us/CorpWeb/CorpSearch/CorpSearch.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_mi": {
        "jurisdiction_code": "us_mi",
        "name": "Michigan",
        "sos_url": "https://cofs.lara.state.mi.us/SearchApi/Search/Search?SearchType=ENTITY_NAME",
        "search_url": "https://cofs.lara.state.mi.us/SearchApi/Search/Search?SearchType=ENTITY_NAME",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_mn": {
        "jurisdiction_code": "us_mn",
        "name": "Minnesota",
        "sos_url": "https://mblsportal.sos.state.mn.us/Business/Search",
        "search_url": "https://mblsportal.sos.state.mn.us/Business/Search",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
        "notes": "Bulk available ~$30; scrape for MVP",
    },
    "us_ms": {
        "jurisdiction_code": "us_ms",
        "name": "Mississippi",
        "sos_url": "https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessIdSearch/portal.aspx",
        "search_url": "https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessIdSearch/portal.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_mo": {
        "jurisdiction_code": "us_mo",
        "name": "Missouri",
        "sos_url": "https://www.sos.mo.gov/BusinessEntity/soskb/csearch.asp",
        "search_url": "https://www.sos.mo.gov/BusinessEntity/soskb/csearch.asp",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_mt": {
        "jurisdiction_code": "us_mt",
        "name": "Montana",
        "sos_url": "https://biz.sosmt.gov/search",
        "search_url": "https://biz.sosmt.gov/search",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ne": {
        "jurisdiction_code": "us_ne",
        "name": "Nebraska",
        "sos_url": "https://www.nebraska.gov/sos/corp/corpsearch.cgi",
        "search_url": "https://www.nebraska.gov/sos/corp/corpsearch.cgi",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_nv": {
        "jurisdiction_code": "us_nv",
        "name": "Nevada",
        "sos_url": "https://esos.nv.gov/EntitySearch/OnlineEntitySearch",
        "search_url": "https://esos.nv.gov/EntitySearch/OnlineEntitySearch",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_nh": {
        "jurisdiction_code": "us_nh",
        "name": "New Hampshire",
        "sos_url": "https://quickstart.sos.nh.gov/online/Account/LandingPage",
        "search_url": "https://quickstart.sos.nh.gov/online/Account/LandingPage",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_nj": {
        "jurisdiction_code": "us_nj",
        "name": "New Jersey",
        "sos_url": "https://www.njportal.com/DOR/BusinessNameSearch",
        "search_url": "https://www.njportal.com/DOR/BusinessNameSearch",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_nm": {
        "jurisdiction_code": "us_nm",
        "name": "New Mexico",
        "sos_url": "https://portal.sos.state.nm.us/BFS/online/CorporationSearch",
        "search_url": "https://portal.sos.state.nm.us/BFS/online/CorporationSearch",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ny": {
        "jurisdiction_code": "us_ny",
        "name": "New York",
        "sos_url": "https://apps.dos.ny.gov/publicInquiry/",
        "search_url": "https://data.ny.gov/api/views/n9v6-gdp6/rows.json?accessType=DOWNLOAD",
        "tier": "bulk",
        "adapter_module": "us.state_registry.bulk.ny",
        "adapter_class": "NewYorkBulkConnector",
    },
    "us_nc": {
        "jurisdiction_code": "us_nc",
        "name": "North Carolina",
        "sos_url": "https://www.sosnc.gov/online_services/search/by_title/_Business_Registration",
        "search_url": "https://www.sosnc.gov/online_services/search/by_title/_Business_Registration",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_nd": {
        "jurisdiction_code": "us_nd",
        "name": "North Dakota",
        "sos_url": "https://firststop.sos.nd.gov/search/business",
        "search_url": "https://firststop.sos.nd.gov/search/business",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_oh": {
        "jurisdiction_code": "us_oh",
        "name": "Ohio",
        "sos_url": "https://businesssearch.ohiosos.gov",
        "search_url": "https://businesssearch.ohiosos.gov",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ok": {
        "jurisdiction_code": "us_ok",
        "name": "Oklahoma",
        "sos_url": "https://www.sos.ok.gov/corp/corpInquiryFind.aspx",
        "search_url": "https://www.sos.ok.gov/corp/corpInquiryFind.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_or": {
        "jurisdiction_code": "us_or",
        "name": "Oregon",
        "sos_url": "https://sos.oregon.gov/business/pages/find.aspx",
        "search_url": "https://data.oregon.gov/resource/tckn-sxa6.json",
        "tier": "bulk",
        "adapter_module": "us.state_registry.bulk.or_",
        "adapter_class": "OregonBulkConnector",
    },
    "us_pa": {
        "jurisdiction_code": "us_pa",
        "name": "Pennsylvania",
        "sos_url": "https://www.corporations.pa.gov/search/corpsearch",
        "search_url": "https://www.corporations.pa.gov/search/corpsearch",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_ri": {
        "jurisdiction_code": "us_ri",
        "name": "Rhode Island",
        "sos_url": "https://business.sos.ri.gov/CorpWeb/CorpSearch/CorpSearch.aspx",
        "search_url": "https://business.sos.ri.gov/CorpWeb/CorpSearch/CorpSearch.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_sc": {
        "jurisdiction_code": "us_sc",
        "name": "South Carolina",
        "sos_url": "https://businessfilings.sc.gov/BusinessFiling/Entity/Search",
        "search_url": "https://businessfilings.sc.gov/BusinessFiling/Entity/Search",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_sd": {
        "jurisdiction_code": "us_sd",
        "name": "South Dakota",
        "sos_url": "https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx",
        "search_url": "https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_tn": {
        "jurisdiction_code": "us_tn",
        "name": "Tennessee",
        "sos_url": "https://tnbear.tn.gov/ECommerce/FilingSearch.aspx",
        "search_url": "https://tnbear.tn.gov/ECommerce/FilingSearch.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_tx": {
        "jurisdiction_code": "us_tx",
        "name": "Texas",
        "sos_url": "https://www.sos.state.tx.us/corp/sosda/index.shtml",
        "search_url": "https://comptroller.texas.gov/taxes/franchise/",
        "tier": "api",
        "adapter_module": "us.state_registry.api.tx",
        "adapter_class": "TexasAPIConnector",
        "notes": "TX Comptroller franchise tax API; SOS bulk ~$1/search",
    },
    "us_ut": {
        "jurisdiction_code": "us_ut",
        "name": "Utah",
        "sos_url": "https://secure.utah.gov/bes/",
        "search_url": "https://secure.utah.gov/bes/",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_vt": {
        "jurisdiction_code": "us_vt",
        "name": "Vermont",
        "sos_url": "https://bizfilings.vermont.gov/online/DatabrainAngular/search/business",
        "search_url": "https://bizfilings.vermont.gov/online/DatabrainAngular/search/business",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_va": {
        "jurisdiction_code": "us_va",
        "name": "Virginia",
        "sos_url": "https://cis.scc.virginia.gov",
        "search_url": "https://cis.scc.virginia.gov",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_wa": {
        "jurisdiction_code": "us_wa",
        "name": "Washington",
        "sos_url": "https://ccfs.sos.wa.gov/",
        "search_url": "https://www.sos.wa.gov/corps/CorpSearch.aspx",
        "tier": "api",
        "adapter_module": "us.state_registry.api.wa",
        "adapter_class": "WashingtonAPIConnector",
    },
    "us_wv": {
        "jurisdiction_code": "us_wv",
        "name": "West Virginia",
        "sos_url": "https://business4.wv.gov/Business/BusinessEntitySearch.aspx",
        "search_url": "https://business4.wv.gov/Business/BusinessEntitySearch.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
        "notes": "Official bulk expensive; scrape for MVP",
    },
    "us_wi": {
        "jurisdiction_code": "us_wi",
        "name": "Wisconsin",
        "sos_url": "https://www.wdfi.org/apps/CorpSearch/Search.aspx",
        "search_url": "https://www.wdfi.org/apps/CorpSearch/Search.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
    "us_wy": {
        "jurisdiction_code": "us_wy",
        "name": "Wyoming",
        "sos_url": "https://wyobiz.wyo.gov/Business/FilingSearch.aspx",
        "search_url": "https://wyobiz.wyo.gov/Business/FilingSearch.aspx",
        "tier": "scrape",
        "adapter_module": "us.state_registry.states.scrape_generic",
        "adapter_class": "GenericScrapedStateConnector",
    },
}

TIER_COUNTS = {
    "bulk": sum(1 for j in JURISDICTIONS.values() if j["tier"] == "bulk"),
    "api": sum(1 for j in JURISDICTIONS.values() if j["tier"] == "api"),
    "scrape": sum(1 for j in JURISDICTIONS.values() if j["tier"] == "scrape"),
    "cobalt": sum(1 for j in JURISDICTIONS.values() if j["tier"] == "cobalt"),
}
