
# ============ PERSON PROFILE GENERATOR ============

def generate_person_profile(person: Dict, company_data: Dict) -> List[str]:
    """Generate 2-4 page profile for each person."""
    md = []
    name = person["name"]
    md.append(f"### {name}")
    md.append("")
    md.append(f"**PayPal Role:** {person['role']}")
    md.append("")
    md.append(f"**Known For:** {person['known_for']}")
    md.append("")

    # Career trajectory
    md.append("#### Career Trajectory")
    md.append("")
    if name == "Peter Thiel":
        md.append("| Period | Role | Organization | Outcome |")
        md.append("|--------|------|--------------|---------|")
        md.append("| 1998-2002 | Co-founder, CEO | PayPal | Sold to eBay $1.5B |")
        md.append("| 2003-present | Co-founder, Chairman | Palantir Technologies | Market cap $300B+ |")
        md.append("| 2004 | First outside investor | Facebook/Meta | $500K → $1B+ return |")
        md.append("| 2005-present | Managing Partner | Founders Fund | AUM ~$12B |")
        md.append("| 2005-present | Managing Partner | Mithril Capital | Growth-stage fund |")
        md.append("| 2014-present | Managing Partner | Valar Ventures | International fintech |")
        md.append("| 2016-2022 | Board Member | Meta Platforms | Resigned 2022 |")
        md.append("")
        md.append("#### Investment Philosophy")
        md.append("")
        md.append("Thiel's investment thesis centers on 'definite optimism' — backing founders with specific, ")
        md.append("contrarian visions of the future. Key principles:")
        md.append("- Monopoly over competition (prefer market-defining companies)")
        md.append("- 'Zero to One' thinking — creating genuinely new things")
        md.append("- Long time horizons with concentrated bets")
        md.append("- Defense/intelligence as inevitable tech frontier")
        md.append("")
        md.append("#### Notable Investments & Returns")
        md.append("")
        md.append("| Investment | Entry | Outcome | Est. Return |")
        md.append("|-----------|-------|---------|-------------|")
        md.append("| Facebook | 2004 ($500K) | IPO 2012 | ~2000x |")
        md.append("| Palantir | 2003 (co-founder) | IPO 2020 | ~1000x+ |")
        md.append("| SpaceX | Early investor | Private ($350B) | ~100x+ |")
        md.append("| Stripe | Founders Fund | Private ($50B+) | ~50x |")
        md.append("| Airbnb | Founders Fund | IPO 2020 | ~100x |")
        md.append("| LinkedIn | Angel | Sold to MSFT $26.2B | ~500x |")
        md.append("")
    elif name == "Elon Musk":
        md.append("| Period | Role | Organization | Outcome |")
        md.append("|--------|------|--------------|---------|")
        md.append("| 1999-2002 | Founder, CEO | X.com/PayPal | Merged, sold to eBay $1.5B |")
        md.append("| 2002-present | CEO, Chief Engineer | SpaceX | Private, ~$350B valuation |")
        md.append("| 2004-present | CEO, Product Architect | Tesla | Market cap ~$800B |")
        md.append("| 2016-present | Co-founder | Neuralink | Brain-computer interface |")
        md.append("| 2016-present | Founder | The Boring Company | Tunneling infrastructure |")
        md.append("| 2022-present | Owner, CTO | X (Twitter) | Acquired $44B |")
        md.append("| 2023-present | Founder | xAI | AI research company |")
        md.append("")
        md.append("#### Wealth & Holdings")
        md.append("")
        md.append("| Asset | Est. Value | % of Net Worth |")
        md.append("|-------|-----------|----------------|")
        md.append("| Tesla equity (~13%) | ~$100B | 35% |")
        md.append("| SpaceX equity (~42%) | ~$147B | 50% |")
        md.append("| X (Twitter) | ~$15B | 5% |")
        md.append("| xAI | ~$20B | 7% |")
        md.append("| Other (Neuralink, Boring Co) | ~$10B | 3% |")
        md.append("")
    elif name == "Reid Hoffman":
        md.append("| Period | Role | Organization | Outcome |")
        md.append("|--------|------|--------------|---------|")
        md.append("| 2000-2002 | COO | PayPal | Sold to eBay |")
        md.append("| 2002-2009 | Co-founder, CEO | LinkedIn | Sold to MSFT $26.2B |")
        md.append("| 2009-present | Partner | Greylock Partners | VC fund |")
        md.append("| 2017-present | Board Member | Microsoft | After LinkedIn acquisition |")
        md.append("| 2023-present | Co-founder | Inflection AI | AI safety company |")
        md.append("")
        md.append("#### Board Positions & Influence")
        md.append("")
        md.append("| Company | Role | Period | Market Cap |")
        md.append("|---------|------|--------|-----------|")
        md.append("| Microsoft | Board Director | 2017-present | ~$3.0T |")
        md.append("| Airbnb | Board Director | 2011-2020 | ~$80B |")
        md.append("| Aurora Innovation | Board Director | 2021-present | ~$5B |")
        md.append("| Blockstream | Investor | 2014-present | Private |")
        md.append("")
    elif name == "Max Levchin":
        md.append("| Period | Role | Organization | Outcome |")
        md.append("|--------|------|--------------|---------|")
        md.append("| 1998-2002 | Co-founder, CTO | PayPal | $1.5B exit |")
        md.append("| 2004 | Co-founder, investor | Yelp | IPO 2012, ~$2.5B |")
        md.append("| 2005-2010 | Founder, CEO | Slide | Sold to Google ~$228M |")
        md.append("| 2012-present | Founder, CEO | Affirm | IPO 2021, ~$15B |")
        md.append("| 2016 | Co-founder | Glow (fertility) | Health tech |")
        md.append("")
        md.append("#### Affirm Business Intelligence")
        md.append("")
        md.append("Affirm (AFRM) represents Levchin's thesis that consumer credit should be transparent. ")
        md.append("The company provides point-of-sale lending with no hidden fees.")
        md.append("")
    elif name == "David Sacks":
        md.append("| Period | Role | Organization | Outcome |")
        md.append("|--------|------|--------------|---------|")
        md.append("| 1999-2002 | COO | PayPal | $1.5B exit |")
        md.append("| 2008-2012 | Founder, CEO | Yammer | Sold to Microsoft $1.2B |")
        md.append("| 2017-present | GP | Craft Ventures | AUM ~$3B |")
        md.append("| 2022-present | Host | All-In Podcast | Political influence |")
        md.append("")
        md.append("#### Craft Ventures Portfolio (Selected)")
        md.append("")
        md.append("| Company | Sector | Stage | Status |")
        md.append("|---------|--------|-------|--------|")
        md.append("| SpaceX | Aerospace | Growth | Private $350B |")
        md.append("| Bird | Mobility | Series C | Public (delisted) |")
        md.append("| ClickUp | Productivity | Series C | Private |")
        md.append("| Sourcegraph | Dev Tools | Series D | Private |")
        md.append("| Relativity Space | Aerospace | Series E | Private |")
        md.append("")
    elif name == "Keith Rabois":
        md.append("| Period | Role | Organization | Outcome |")
        md.append("|--------|------|--------------|---------|")
        md.append("| 2000-2002 | EVP | PayPal | $1.5B exit |")
        md.append("| 2010-2013 | COO | Square (Block) | IPO 2015 |")
        md.append("| 2013-2019 | Partner | Khosla Ventures | VC |")
        md.append("| 2019-present | Managing Director | Founders Fund | VC |")
        md.append("")
        md.append("#### Board Seats (Active & Former)")
        md.append("")
        md.append("| Company | Ticker | Role | Period |")
        md.append("|---------|--------|------|--------|")
        md.append("| Yelp | YELP | Board Director | 2004-present |")
        md.append("| DoorDash | DASH | Board Director | 2016-present |")
        md.append("| Robinhood | HOOD | Board Director | 2020-present |")
        md.append("| Affirm | AFRM | Investor/Advisor | 2012-2018 |")
        md.append("")
    elif name == "Joe Lonsdale":
        md.append("| Period | Role | Organization | Outcome |")
        md.append("|--------|------|--------------|---------|")
        md.append("| 2002-2003 | Intern | PayPal (via Clarium) | Thiel mentee |")
        md.append("| 2003-present | Co-founder | Palantir Technologies | IPO 2020, $300B+ |")
        md.append("| 2009-present | Founder, GP | 8VC (Formation 8) | AUM ~$5B |")
        md.append("| 2009-present | Founder | Addepar | Wealth management platform |")
        md.append("| 2021-present | Founder | Epirus | Directed energy defense |")
        md.append("")
        md.append("#### 8VC Portfolio Focus")
        md.append("")
        md.append("8VC focuses on 'industries of the future': defense tech, biotech, real estate tech, logistics.")
        md.append("")
        md.append("| Company | Sector | Notable |")
        md.append("|---------|--------|---------|")
        md.append("| Anduril | Defense | Autonomous defense systems |")
        md.append("| Epirus | Defense | Directed energy weapons |")
        md.append("| Joby Aviation | Air mobility | eVTOL aircraft |")
        md.append("| Oscar Health | Healthcare | Health insurance tech |")
        md.append("| Opendoor | Real estate | iBuying platform |")
        md.append("")
    elif name == "Roelof Botha":
        md.append("| Period | Role | Organization | Outcome |")
        md.append("|--------|------|--------------|---------|")
        md.append("| 2000-2003 | CFO | PayPal | $1.5B exit |")
        md.append("| 2003-present | Partner → Managing Partner | Sequoia Capital | AUM ~$85B |")
        md.append("")
        md.append("#### Sequoia Investments (Botha-led)")
        md.append("")
        md.append("| Company | Entry Stage | Outcome | Sector |")
        md.append("|---------|-----------|---------|--------|")
        md.append("| YouTube | Series A | Sold to Google $1.65B | Video |")
        md.append("| Square/Block | Series A | IPO, ~$40B | Fintech |")
        md.append("| MongoDB | Series B | IPO, ~$25B | Database |")
        md.append("| Unity | Growth | IPO, ~$15B | Gaming |")
        md.append("| Instagram | Early | Sold to Meta $1B | Social |")
        md.append("| Eventbrite | Series A | IPO | Events |")
        md.append("")
    else:
        md.append(f"*Career details being researched for {name}.*")
        md.append("")

    # Show their companies' current data
    person_tickers = person.get("companies", [])
    if person_tickers:
        md.append(f"#### Portfolio Companies — Live Financial Data")
        md.append("")
        for ticker in person_tickers:
            if ticker in company_data:
                fin = company_data[ticker].get("financials", {})
                price = fin.get("price")
                if price:
                    mc = fin.get("market_cap", 0)
                    info = COMPANIES_FULL.get(ticker, {})
                    md.append(f"**{info.get('name', ticker)} ({ticker})**")
                    md.append("")
                    md.append(f"- Price: ${price:.2f} | Market Cap: {fmt_money(mc)}")
                    md.append(f"- P/E: {fin.get('pe_ttm', 'N/A')} | P/S: {fin.get('ps_ttm', 'N/A')} | Beta: {fin.get('beta', 'N/A')}")
                    consensus = fin.get("consensus", {})
                    if consensus.get("target_consensus"):
                        md.append(f"- Analyst Target: ${consensus['target_consensus']:.2f} | Bullish: {consensus.get('bullish_pct', 'N/A')}%")
                    md.append("")

    # Funds
    if person.get("funds"):
        md.append("#### Fund Operations")
        md.append("")
        for fund in person["funds"]:
            md.append(f"- **{fund}**")
        md.append("")

    md.append("")
    return md
