
# ============ REPORT GENERATION ============

def generate_full_report(company_data: Dict, people: List, charts: Dict) -> str:
    """Generate 50-80 page markdown report."""
    md = []

    # TITLE PAGE
    md.append("# PayPal Mafia — Deep Intelligence Network Report")
    md.append("")
    md.append(f"**Generated:** {datetime.now().strftime('%B %d, %Y')}")
    md.append("")
    md.append("**Classification:** CONFIDENTIAL — For Internal Research Only")
    md.append("")
    md.append("---")
    md.append("")

    # TABLE OF CONTENTS
    md.append("## Table of Contents")
    md.append("")
    md.append("1. Executive Summary")
    md.append("2. Network Overview & Key Findings")
    md.append("3. Individual Deep Profiles")
    md.append("4. Company Intelligence Dossiers")
    md.append("5. Cross-Portfolio Analysis")
    md.append("6. Government & Political Intelligence")
    md.append("7. Investment Network & Fund Analysis")
    md.append("8. Risk Assessment & Correlations")
    md.append("9. Network Visualizations")
    md.append("10. Methodology & Data Sources")
    md.append("")
    md.append("---")
    md.append("")

    # EXECUTIVE SUMMARY
    md.append("## 1. Executive Summary")
    md.append("")
    total_mc = sum(d.get("financials", {}).get("market_cap", 0) for d in company_data.values())
    md.append(f"The PayPal Mafia represents one of the most consequential networks in modern capitalism. ")
    md.append(f"This report traces **{len(people)} core members** across **{len(company_data)} public companies** ")
    md.append(f"with a combined market capitalization of **{fmt_money(total_mc)}**.")
    md.append("")
    md.append("### Key Network Statistics")
    md.append("")
    md.append("| Metric | Value |")
    md.append("|--------|-------|")
    md.append(f"| Core Members Analyzed | {len(people)} |")
    md.append(f"| Public Companies Tracked | {len(company_data)} |")
    md.append(f"| Combined Public Market Cap | {fmt_money(total_mc)} |")
    md.append(f"| Est. Private Portfolio Value | $500B+ (SpaceX, Stripe, etc.) |")
    md.append(f"| Venture Funds Operated | {sum(len(p.get('funds', [])) for p in people)} |")
    md.append(f"| Sectors Dominated | Technology, Fintech, Defense, Social, Energy |")
    md.append(f"| Government Contract Value | ${sum(float(d.get('contracts', {}).get('total_obligations', 0) or 0) for d in company_data.values())/1e9:.1f}B+ |")
    md.append("")
    md.append("### Critical Findings")
    md.append("")
    md.append("1. **Concentration of Power**: A single PayPal cohort of ~16 people controls or influences companies worth >$5 trillion")
    md.append("2. **Defense-Tech Nexus**: Palantir (Thiel/Lonsdale) has become a primary intelligence platform for US/Allied governments")
    md.append("3. **Financial Infrastructure**: Block, Affirm, Robinhood — mafia members rebuilt payments from scratch post-PayPal")
    md.append("4. **Political Influence**: Through lobbying ($100M+), donations, ambassadorships, and advisory roles")
    md.append("5. **Venture Multiplication**: Founders Fund, Sequoia, 8VC, Craft Ventures fund the next generation of mafia-adjacent companies")
    md.append("")
    md.append("---")
    md.append("")

    # NETWORK OVERVIEW
    md.append("## 2. Network Overview & Key Findings")
    md.append("")
    md.append("### The PayPal Origin (1998-2002)")
    md.append("")
    md.append("PayPal was founded in December 1998 as Confinity by Peter Thiel, Max Levchin, and Luke Nosek. ")
    md.append("It merged with Elon Musk's X.com in 2000. The company went public in February 2002 and was ")
    md.append("acquired by eBay for $1.5 billion in October 2002. This relatively brief period created a ")
    md.append("network of entrepreneurs who would go on to found, fund, or lead companies worth trillions.")
    md.append("")
    md.append("### Network Formation Patterns")
    md.append("")
    md.append("The PayPal Mafia exhibits three distinct patterns of network propagation:")
    md.append("")
    md.append("**Pattern 1: Serial Founding**")
    md.append("Members who left PayPal to found entirely new companies:")
    md.append("- Elon Musk → Tesla, SpaceX, Neuralink, The Boring Company, xAI")
    md.append("- Max Levchin → Slide (sold to Google), Affirm")
    md.append("- Jeremy Stoppelman + Russel Simmons → Yelp")
    md.append("- Chad Hurley + Steve Chen + Jawed Karim → YouTube")
    md.append("- David Sacks → Yammer (sold to Microsoft), Craft Ventures")
    md.append("- Joe Lonsdale → Palantir, Addepar, 8VC")
    md.append("")
    md.append("**Pattern 2: Venture Capital Multiplication**")
    md.append("Members who became VCs, funding hundreds of subsequent companies:")
    md.append("- Peter Thiel → Founders Fund (AUM ~$12B), Mithril Capital, Valar Ventures")
    md.append("- Roelof Botha → Sequoia Capital (AUM ~$85B)")
    md.append("- Keith Rabois → Khosla Ventures → Founders Fund")
    md.append("- Luke Nosek + Ken Howery → Founders Fund, Gigafund")
    md.append("- David Sacks → Craft Ventures (AUM ~$3B)")
    md.append("- Joe Lonsdale → 8VC (AUM ~$5B)")
    md.append("")
    md.append("**Pattern 3: Board Interlocking**")
    md.append("Members serving on each other's boards and co-investing:")
    md.append("- Peter Thiel: Board of Facebook/Meta, Palantir, Founders Fund portfolio companies")
    md.append("- Keith Rabois: Board of Square, Yelp, DoorDash, Robinhood")
    md.append("- Reid Hoffman: Board of Microsoft, Airbnb, Aurora")
    md.append("")
    md.append("### Educational Background Correlation")
    md.append("")
    md.append("| University | Members | Post-PayPal Impact |")
    md.append("|-----------|---------|-------------------|")
    md.append("| Stanford University | Thiel, Sacks, Rabois, Lonsdale, Stoppelman | Dominant in VC formation |")
    md.append("| University of Illinois | Levchin, Chen | Technical founders |")
    md.append("| Indiana University (Penn) | Hurley | Creative/design leadership |")
    md.append("| Stanford Law | Thiel, Howery | Legal/strategic focus |")
    md.append("")
    md.append("---")
    md.append("")

    # INDIVIDUAL DEEP PROFILES
    md.append("## 3. Individual Deep Profiles")
    md.append("")
    md.append("Comprehensive intelligence on each PayPal Mafia member: their ventures, investments, ")
    md.append("board positions, political activities, and financial footprint.")
    md.append("")

    for person in people:
        md.extend(generate_person_profile(person, company_data))

    md.append("---")
    md.append("")

    # COMPANY INTELLIGENCE DOSSIERS
    md.append("## 4. Company Intelligence Dossiers")
    md.append("")
    md.append("Full financial, lobbying, government contract, and institutional ownership analysis ")
    md.append("for each major public company in the PayPal Mafia portfolio.")
    md.append("")

    for ticker, data in company_data.items():
        md.extend(generate_company_dossier(ticker, data))

    md.append("---")
    md.append("")

    # CROSS-PORTFOLIO ANALYSIS
    md.append("## 5. Cross-Portfolio Analysis")
    md.append("")
    md.extend(generate_cross_analysis(company_data, people))
    md.append("")
    md.append("---")
    md.append("")

    # GOVERNMENT & POLITICAL
    md.append("## 6. Government & Political Intelligence")
    md.append("")
    md.extend(generate_political_section(company_data, people))
    md.append("")
    md.append("---")
    md.append("")

    # INVESTMENT NETWORK
    md.append("## 7. Investment Network & Fund Analysis")
    md.append("")
    md.extend(generate_fund_analysis(people))
    md.append("")
    md.append("---")
    md.append("")

    # RISK ASSESSMENT
    md.append("## 8. Risk Assessment & Correlations")
    md.append("")
    md.extend(generate_risk_section(company_data, people))
    md.append("")
    md.append("---")
    md.append("")

    # CHARTS
    md.append("## 9. Network Visualizations")
    md.append("")
    for chart_name, chart_b64 in charts.items():
        title = chart_name.replace("_", " ").title()
        md.append(f"### {title}")
        md.append("")
        md.append(f"![{title}](data:image/png;base64,{chart_b64})")
        md.append("")

    md.append("---")
    md.append("")

    # METHODOLOGY
    md.append("## 10. Methodology & Data Sources")
    md.append("")
    md.append("| Source | Data Type | Coverage |")
    md.append("|--------|-----------|----------|")
    md.append("| SEC EDGAR | Insider transactions, 13F filings, Form D | All public companies |")
    md.append("| SEC EFTS | Full-text search for person CIKs, filings | Historical |")
    md.append("| Finnhub | Real-time market data, analyst ratings | Live |")
    md.append("| Financial Modeling Prep | Financials, targets, quotes | Current + historical |")
    md.append("| USASpending.gov | Federal contract awards | FY2008-present |")
    md.append("| OpenSecrets/FEC | Lobbying spend, PAC contributions | 2010-present |")
    md.append("| Senate LDA | Lobbying disclosure registrations | Current |")
    md.append("| NewsAPI | Recent news coverage | 30 days |")
    md.append("")
    md.append("**Limitations:**")
    md.append("- Private company valuations (SpaceX, Stripe) are estimates from secondary markets")
    md.append("- Venture fund returns are not publicly disclosed")
    md.append("- Some international lobbying may not be captured by US-focused sources")
    md.append("- LinkedIn data not included due to ToS restrictions")
    md.append("")

    return "\n".join(md)
